name: Jitendra Chaturvedi Photography
favicon: null
layout_spectrum: 0.19283
typography_spectrum: 0.14242
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#222222'
    - '#cdcdcd'
    - '#ebebeb'
    - '#919191'
    - '#646464'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
