name: Jitendra Chaturvedi Photography
favicon: null
layout_spectrum: 0.19283
typography_spectrum: 0.14242
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#222222'
    - '#cdcdcd'
    - '#ebebeb'
    - '#919191'
    - '#646464'
  brandStrength: 0.1875
  lightness: 0.125
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
